### ISSUE TITLE
カテゴリに属する投稿がない場合の表示

### ISSUE THREAD

**Issue by zzzzzz21** [zzzzzz21/ripple-c#2]
http://www.ripple-c.jp/wp/
http://www.ripple-c.jp/wp/news/

「採用情報」「入居説明会」に属する記事がありません。
記事がないカテゴリの欄には、「このカテゴリのお知らせはありません。」と表示してもらえますでしょうか。

**Comment by kobaatsu** [comment]
@zzzzzz21 
対応しました。

http://www.ripple-c.jp/wp/news

シンプルにPタグで囲っただけですので、スタイルの指定が欲しい場合はご指示ください。

**Comment by zzzzzz21** [comment]
@kobaatsu 
これも充分だと思います、ありがとうございます。

それでは、全体をドメイン直下で公開していただけますでしょうか。

**Comment by kobaatsu** [comment]
公開については別issue #6 としました。
こちらクローズします。
