### ISSUE TITLE
デフォルトのキーワード設定はどこでやっていますか？

### ISSUE THREAD

**Issue by zzzzzz21** [zzzzzz21/ripple-c#3]
場所がわかればこちらで対応します！

**Comment by kobaatsu** [comment]
トップページの（固定ページ->TOP）のカスタムフィールドです。

> カスタムフィールドが空いている場合はそれぞれ全体のdescription,トップページのkeywordを拾ってくるように（とりあえず）しています。

とりあえず、ですので他に相応しい箇所があれば変更します。

**Comment by zzzzzz21** [comment]
了解しました。
充分だと思いますので、箇所の変更なしでOKです。

この項、終了します。
