### ISSUE TITLE
お知らせのdescription,keywords設定

### ISSUE THREAD

**Issue by zzzzzz21** [zzzzzz21/ripple-c#7]
http://www.ripple-c.jp/wp/wp-admin/post.php?post=36&action=edit

カスタムフィールドで上書き設定しましたが、反映されませんでした。
設定方法が違いますか？

**Comment by kobaatsu** [comment]
投稿ページではニュースと同一にしておいたのですが、投稿ページでもkeyword,descriptionを設定できるようにしました。
未設定の場合、ニュースのkeyword,descriptionを持ってきます。
